baseURL = ""
languageCode = "en-us"
title = "Blenderbox"
theme = "blenderbox"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -110

  [[menu.main]]
    name = "Style Guide"
    url = "/style-guide/"
    weight = -100

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = -90

  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = -90

# html in md
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true
